version: '3.7'
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - '8080:8080'
    links: 
      - mongo
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - '27017:27017'
